# Generated by Django 5.0.6 on 2026-07-11 09:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delta', models.IntegerField(help_text='Positive to add stock, negative to remove.')),
                ('reason', models.CharField(choices=[('RESTOCK', 'Restock'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('DAMAGE', 'Damage / write-off'), ('CORRECTION', 'Manual correction')], max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'stock_adjustments',
                'ordering': ['-created_at'],
            },
        ),
    ]
