# Generated by Django 5.0.6 on 2026-07-11 09:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_registration_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('business_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('shipping_address', models.TextField(blank=True)),
                ('billing_address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending approval'), ('ACTIVE', 'Active'), ('DEACTIVATED', 'Deactivated')], default='PENDING', max_length=16)),
            ],
            options={
                'db_table': 'sellers',
            },
        ),
    ]
