import React, { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import client, { API_ORIGIN, apiErrorMessage } from "../api/client.js";
import { useAuth } from "../context/AuthContext.jsx";
import "./ProductDetail.css";

const messageFor = apiErrorMessage;
const imageUrl = (url) => url && (url.startsWith("http") ? url : `${API_ORIGIN}${url.startsWith("/") ? "" : "/"}${url}`);

function Stars({ value, onChange, label = "Rating" }) {
  return <div className="stars" aria-label={label}>{[1, 2, 3, 4, 5].map((star) => <button key={star} type="button" className={star <= value ? "star selected" : "star"} onClick={() => onChange?.(star)} disabled={!onChange} aria-label={`${star} star${star === 1 ? "" : "s"}`}>★</button>)}</div>;
}

export default function ProductDetail() {
  const { id } = useParams(); const { user } = useAuth();
  const [product, setProduct] = useState(null); const [reviews, setReviews] = useState([]); const [loading, setLoading] = useState(true);
  const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [rating, setRating] = useState(5);
  const [comment, setComment] = useState(""); const [reviewImage, setReviewImage] = useState(null); const [submitting, setSubmitting] = useState(false);
  const load = async (showLoader = true) => { if (showLoader) setLoading(true); setError(""); try { const [detail, reviewList] = await Promise.all([client.get(`/catalog/products/${id}/`), client.get(`/reviews/product/${id}/`)]); setProduct(detail.data); setReviews(reviewList.data?.results || reviewList.data || []); } catch (err) { setError(messageFor(err, "The requested product was not found.")); } finally { if (showLoader) setLoading(false); } };
  useEffect(() => { void load(); }, [id]);
  const addToCart = async () => { const variant = product?.variants?.find((item) => item.in_stock) || product?.variants?.[0]; if (!variant) { setError("This product has no purchasable variant yet."); return; } try { await client.post("/cart/items/", { variant: variant.id, quantity: 1 }); setNotice("Product added to cart."); } catch (err) { setError(messageFor(err, "Could not add this product to your cart.")); } };
  const submitReview = async (event) => { event.preventDefault(); setSubmitting(true); setError(""); setNotice(""); try { const payload = new FormData(); payload.append("product", id); payload.append("rating", String(rating)); payload.append("comment", comment); if (reviewImage) payload.append("image", reviewImage); const { data } = await client.post("/reviews/", payload); setReviews((current) => [data, ...current.filter((item) => item.id !== data.id)]); setComment(""); setReviewImage(null); const fileInput = document.getElementById("review-image-input"); if (fileInput) fileInput.value = ""; setNotice("Review submitted and published."); await load(false); } catch (err) { setError(messageFor(err, "Could not submit your review.")); } finally { setSubmitting(false); } };
  if (loading) return <div className="container"><p>Loading product…</p></div>;
  if (error && !product) return <div className="container"><h2>Product unavailable</h2><p className="error">{error}</p><Link to="/products">Return to catalog</Link></div>;
  const primary = product.images?.find((item) => item.is_primary) || product.images?.[0]; const stock = (product.variants || []).reduce((total, item) => total + (item.stock_quantity || 0), 0); const isBuyerAccount = user?.role === "CUSTOMER";
  return <main className="container product-detail-page"><Link className="back-link" to="/products">← Back to catalog</Link>{error && <p className="error">{error}</p>}{notice && <p className="badge">{notice}</p>}<section className="product-detail-card"><div className="product-detail-image">{primary ? <img src={imageUrl(primary.image)} alt={product.name} /> : <div className="image-placeholder">No photo yet</div>}</div><div className="product-detail-info"><span className="eyebrow">{product.category_name || "Product"}</span><h1>{product.name}</h1>{product.store_id && <p className="store-line"><strong>Store:</strong> <Link to={`/stores/${product.store_id}`}>{product.store_name}</Link>{product.store_owner_name ? ` · ${product.store_owner_name}` : ""}</p>}<p className="detail-price">${product.base_price}</p><div className="rating-summary"><Stars value={Math.round(product.rating || 0)} /> <span>{product.rating ? `${product.rating} / 5` : "No ratings yet"}{product.review_count ? ` · ${product.review_count} reviews` : ""}</span></div><p><strong>Stock:</strong> {stock}</p><p className="description">{product.description || "No description provided."}</p>{isBuyerAccount && <button onClick={addToCart}>Add to Cart</button>}</div></section><section className="reviews-section"><h2>Reviews</h2>{reviews.length ? reviews.map((review) => <article className="review-card" key={review.id}><div><Stars value={review.rating} /><strong>{review.customer_name}</strong><time>{review.created_at ? new Date(review.created_at).toLocaleDateString() : ""}</time></div>{review.comment && <p>{review.comment}</p>}{review.image && <img className="review-image" src={imageUrl(review.image)} alt="Review attachment" />}</article>) : <p>No reviews yet.</p>}{isBuyerAccount && <form className="review-form" onSubmit={submitReview}><h3>Write a Review</h3><label>Your rating</label><Stars value={rating} onChange={setRating} label="Choose your rating" /><label htmlFor="review-comment">Review</label><textarea id="review-comment" value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Share your experience" /><label htmlFor="review-image-input">Add an image <span>(optional)</span></label><input id="review-image-input" type="file" accept="image/*" onChange={(event) => setReviewImage(event.target.files?.[0] || null)} /><button disabled={submitting}>{submitting ? "Submitting…" : "Submit Review"}</button></form>}</section></main>;
}
