# Generated by Django 5.0.6 on 2026-07-11 09:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carrier', models.CharField(max_length=100)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PREPARING', 'Preparing'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered')], default='PREPARING', max_length=16)),
                ('estimated_arrival', models.DateField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='sellers.seller')),
            ],
            options={
                'db_table': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
    ]
